# Generated by Django 5.0.6 on 2024-05-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
